
export const cards = [
    { suit: "Hearts", value: "Ace", color: "red", shape: "heart" },
    { suit: "Hearts", value: "2", color: "red", shape: "heart" },
    // { suit: "Hearts", value: "3", color: "red", shape: "heart" },
    // { suit: "Hearts", value: "4", color: "red", shape: "heart" },
    // { suit: "Hearts", value: "5", color: "red", shape: "heart" },
    // { suit: "Hearts", value: "6", color: "red", shape: "heart" },
    // { suit: "Hearts", value: "7", color: "red", shape: "heart" },
    // { suit: 'Hearts', value: '8', color: 'red', shape: 'heart' },
    // { suit: 'Hearts', value: '9', color: 'red', shape: 'heart' },
    // { suit: 'Hearts', value: '10', color: 'red', shape: 'heart' },
    // { suit: 'Hearts', value: 'Jack', color: 'red', shape: 'heart' },
    // { suit: 'Hearts', value: 'Queen', color: 'red', shape: 'heart' },
    // { suit: 'Hearts', value: 'King', color: 'red', shape: 'heart' },
    // { suit: "Diamonds", value: "Ace", color: "red", shape: "diamond" },
    // { suit: "Diamonds", value: "2", color: "red", shape: "diamond" },
    // { suit: "Diamonds", value: "3", color: "red", shape: "diamond" },
    // { suit: "Diamonds", value: "4", color: "red", shape: "diamond" },
    // { suit: "Diamonds", value: "5", color: "red", shape: "diamond" },
    // { suit: "Diamonds", value: "6", color: "red", shape: "diamond" },
    // { suit: "Diamonds", value: "7", color: "red", shape: "diamond" },
    // { suit: 'Diamonds', value: '8', color: 'red', shape: 'diamond' },
    // { suit: 'Diamonds', value: '9', color: 'red', shape: 'diamond' },
    // { suit: 'Diamonds', value: '10', color: 'red', shape: 'diamond' },
    // { suit: 'Diamonds', value: 'Jack', color: 'red', shape: 'diamond' },
    // { suit: 'Diamonds', value: 'Queen', color: 'red', shape: 'diamond' },
    // { suit: 'Diamonds', value: 'King', color: 'red', shape: 'diamond' },
    // { suit: "Clubs", value: "Ace", color: "black", shape: "club" },
    // { suit: "Clubs", value: "2", color: "black", shape: "club" },
    // { suit: "Clubs", value: "3", color: "black", shape: "club" },
    // { suit: "Clubs", value: "4", color: "black", shape: "club" },
    // { suit: "Clubs", value: "5", color: "black", shape: "club" },
    // { suit: "Clubs", value: "6", color: "black", shape: "club" },
    // { suit: "Clubs", value: "7", color: "black", shape: "club" },
    // { suit: 'Clubs', value: '8', color: 'black', shape: 'club' },
    // { suit: 'Clubs', value: '9', color: 'black', shape: 'club' },
    // { suit: 'Clubs', value: '10', color: 'black', shape: 'club' },
    // { suit: 'Clubs', value: 'Jack', color: 'black', shape: 'club' },
    // { suit: 'Clubs', value: 'Queen', color: 'black', shape: 'club' },
    // { suit: 'Clubs', value: 'King', color: 'black', shape: 'club' },
    // { suit: "Spades", value: "Ace", color: "black", shape: "spade" },
    // { suit: "Spades", value: "2", color: "black", shape: "spade" },
    // { suit: "Spades", value: "3", color: "black", shape: "spade" },
    // { suit: "Spades", value: "4", color: "black", shape: "spade" },
    // { suit: "Spades", value: "5", color: "black", shape: "spade" },
    // { suit: "Spades", value: "6", color: "black", shape: "spade" },
    // { suit: "Spades", value: "7", color: "black", shape: "spade" },
    // { suit: 'Spades', value: '8', color: 'black', shape: 'spade' },
    // { suit: 'Spades', value: '9', color: 'black', shape: 'spade' },
    // { suit: 'Spades', value: '10', color: 'black', shape: 'spade' },
    // { suit: 'Spades', value: 'Jack', color: 'black', shape: 'spade' },
    // { suit: 'Spades', value: 'Queen', color: 'black', shape: 'spade' },
    // { suit: 'Spades', value: 'King', color: 'black', shape: 'spade' },
    // { suit: 'Joker', value: 'Joker', color: 'red', shape: 'joker' },
    // { suit: 'Joker', value: 'Joker', color: 'black', shape: 'joker' }
  ];


  export default {
    cards
  };